In [99]:
from unittest.mock import inplace

import numpy as np , pandas as pd

In [100]:
age_group = np.array([
"18-25","18-25","18-25","18-25","18-25","18-25","18-25","18-25",
"26-35","26-35","26-35","26-35","26-35","26-35","26-35","26-35",
"36-45","36-45","36-45","36-45","36-45","36-45","36-45","36-45",
"46-60","46-60","46-60","46-60","46-60","46-60","46-60","46-60",
"61-75","61-75","61-75","61-75","61-75","61-75",
"76-100","76-100","76-100","76-100"
])

income = np.array([
3.2,4.1,2.8,3.6,np.nan,4.5,3.9,2.5,
6.5,7.2,np.nan,8.0,6.9,7.5,9.1,6.2,
10.5,11.2,9.8,np.nan,12.1,10.9,11.5,13.0,
14.5,15.2,13.8,16.1,np.nan,15.4,14.9,16.5,
12.2,11.8,np.nan,10.5,12.9,11.4,
8.1,np.nan,7.5,6.8
])

data = dict()
data['age_grp'] = age_group
data['income'] = np.round(income * 100000,2)

In [101]:
dataset = pd.DataFrame(data)
display(dataset)

   age_grp     income
0    18-25   320000.0
1    18-25   410000.0
2    18-25   280000.0
3    18-25   360000.0
4    18-25        NaN
5    18-25   450000.0
6    18-25   390000.0
7    18-25   250000.0
8    26-35   650000.0
9    26-35   720000.0
10   26-35        NaN
11   26-35   800000.0
12   26-35   690000.0
13   26-35   750000.0
14   26-35   910000.0
15   26-35   620000.0
16   36-45  1050000.0
17   36-45  1120000.0
18   36-45   980000.0
19   36-45        NaN
20   36-45  1210000.0
21   36-45  1090000.0
22   36-45  1150000.0
23   36-45  1300000.0
24   46-60  1450000.0
25   46-60  1520000.0
26   46-60  1380000.0
27   46-60  1610000.0
28   46-60        NaN
29   46-60  1540000.0
30   46-60  1490000.0
31   46-60  1650000.0
32   61-75  1220000.0
33   61-75  1180000.0
34   61-75        NaN
35   61-75  1050000.0
36   61-75  1290000.0
37   61-75  1140000.0
38  76-100   810000.0
39  76-100        NaN
40  76-100   750000.0
41  76-100   680000.0

In [102]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   age_grp  42 non-null     object
 1   income   36 non-null     float64
dtypes: float64(1), object(1)
memory usage: 804.0+ bytes

In [103]:
dataset.describe()

             income
count  3.600000e+01
mean   9.516667e+05
std    4.125565e+05
min    2.500000e+05
25%    6.725000e+05
50%    1.015000e+06
75%    1.237500e+06
max    1.650000e+06

In [104]:
dataset.fillna({'income':dataset['income'].mean()},inplace=True)
dataset['income'].astype('int')
dataset

   age_grp        income
0    18-25  3.200000e+05
1    18-25  4.100000e+05
2    18-25  2.800000e+05
3    18-25  3.600000e+05
4    18-25  9.516667e+05
5    18-25  4.500000e+05
6    18-25  3.900000e+05
7    18-25  2.500000e+05
8    26-35  6.500000e+05
9    26-35  7.200000e+05
10   26-35  9.516667e+05
11   26-35  8.000000e+05
12   26-35  6.900000e+05
13   26-35  7.500000e+05
14   26-35  9.100000e+05
15   26-35  6.200000e+05
16   36-45  1.050000e+06
17   36-45  1.120000e+06
18   36-45  9.800000e+05
19   36-45  9.516667e+05
20   36-45  1.210000e+06
21   36-45  1.090000e+06
22   36-45  1.150000e+06
23   36-45  1.300000e+06
24   46-60  1.450000e+06
25   46-60  1.520000e+06
26   46-60  1.380000e+06
27   46-60  1.610000e+06
28   46-60  9.516667e+05
29   46-60  1.540000e+06
30   46-60  1.490000e+06
31   46-60  1.650000e+06
32   61-75  1.220000e+06
33   61-75  1.180000e+06
34   61-75  9.516667e+05
35   61-75  1.050000e+06
36   61-75  1.290000e+06
37   61-75  1.140000e+06
38  76-100  8.100000e+05
39  76-100  9.516667e+05
40  76-100  7.500000e+05
41  76-100  6.800000e+05

In [105]:
df_age = dataset.groupby('age_grp')
df_age.describe()

        income                                                         \
         count          mean            std            min        25%
age_grp
18-25      8.0  4.264583e+05  222433.220762  250000.000000   310000.0
26-35      8.0  7.614583e+05  118995.256341  620000.000000   680000.0
36-45      8.0  1.106458e+06  115677.567416  951666.666667  1032500.0
46-60      8.0  1.448958e+06  218248.688609  951666.666667  1432500.0
61-75      6.0  1.138611e+06  121702.810461  951666.666667  1072500.0
76-100     4.0  7.979167e+05  115449.002690  680000.000000   732500.0


               50%           75%           max
age_grp
18-25     375000.0  4.200000e+05  9.516667e+05
26-35     735000.0  8.275000e+05  9.516667e+05
36-45    1105000.0  1.165000e+06  1.300000e+06
46-60    1505000.0  1.557500e+06  1.650000e+06
61-75    1160000.0  1.210000e+06  1.290000e+06
76-100    780000.0  8.454167e+05  9.516667e+05

In [106]:
display(df_age.get_group('18-25'))
df_age.groups

  age_grp         income
0   18-25  320000.000000
1   18-25  410000.000000
2   18-25  280000.000000
3   18-25  360000.000000
4   18-25  951666.666667
5   18-25  450000.000000
6   18-25  390000.000000
7   18-25  250000.000000

{'18-25': [0, 1, 2, 3, 4, 5, 6, 7], '26-35': [8, 9, 10, 11, 12, 13, 14, 15], '36-45': [16, 17, 18, 19, 20, 21, 22, 23], '46-60': [24, 25, 26, 27, 28, 29, 30, 31], '61-75': [32, 33, 34, 35, 36, 37], '76-100': [38, 39, 40, 41]}

In [107]:
list_inc = df_age['income'].apply(list)
list_inc

age_grp
18-25     [320000.0, 410000.0, 280000.0, 360000.0, 95166...
26-35     [650000.0, 720000.0, 951666.6666666666, 800000...
36-45     [1050000.0, 1120000.0, 980000.0, 951666.666666...
46-60     [1450000.0, 1520000.0, 1380000.0, 1610000.0, 9...
61-75     [1220000.0, 1180000.0, 951666.6666666666, 1050...
76-100    [810000.0, 951666.6666666666, 750000.0, 680000.0]
Name: income, dtype: object

In [113]:
iris = pd.read_csv('iris.csv')
display(iris)
iris.columns = ['SepalLengthCm','SepalWidthCm','PetalLengthC','PetalWidthCm','Species']

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [112]:
iris

     SepalLengthCm  SepalWidthCm  PetalLengthC  PetalWidthCm         Species
0              4.9           3.0           1.4           0.2     Iris-setosa
1              4.7           3.2           1.3           0.2     Iris-setosa
2              4.6           3.1           1.5           0.2     Iris-setosa
3              5.0           3.6           1.4           0.2     Iris-setosa
4              5.4           3.9           1.7           0.4     Iris-setosa
..             ...           ...           ...           ...             ...
144            6.7           3.0           5.2           2.3  Iris-virginica
145            6.3           2.5           5.0           1.9  Iris-virginica
146            6.5           3.0           5.2           2.0  Iris-virginica
147            6.2           3.4           5.4           2.3  Iris-virginica
148            5.9           3.0           5.1           1.8  Iris-virginica

[149 rows x 5 columns]

In [115]:
df_spec = iris.groupby('Species')
display(df_spec.describe())

                SepalLengthCm                                                 \
                        count      mean       std  min    25%  50%  75%  max
Species
Iris-setosa              49.0  5.004082  0.355879  4.3  4.800  5.0  5.2  5.8
Iris-versicolor          50.0  5.936000  0.516171  4.9  5.600  5.9  6.3  7.0
Iris-virginica           50.0  6.588000  0.635880  4.9  6.225  6.5  6.9  7.9

                SepalWidthCm            ... PetalLengthC      PetalWidthCm  \
                       count      mean  ...          75%  max        count
Species                                 ...
Iris-setosa             49.0  3.416327  ...        1.600  1.9         49.0
Iris-versicolor         50.0  2.770000  ...        4.600  5.1         50.0
Iris-virginica          50.0  2.974000  ...        5.875  6.9         50.0


                     mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244898  0.108130  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326000  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026000  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]