In [1]:
# Dataset size - 1 million
import pandas as pd
import numpy as np

In [2]:
SEED = 42
#np.random.seed(SEED)
NUM_ROWS = 10000

In [3]:
RANGES = {
    'STUDENT_IDS' : (26090000, 26900000),
    'MATH_SCORE' : (0, 300),
    'PHYSICS_SCORE' : (0, 300),
    'CHEMISTRY_SCORE' : (0, 300),
    'BIOLOGY_SCORE' : (0, 300),
    'ATTENDANCE' : (0.00, 100.00),
    'PERCENTILE' : (0.00, 100.00),
    'GENDER' : ['MALE', 'FEMALE', 'OTHER'],
    'PARENT_EDUCATION' : [
        "No formal education", "Primary School", "Secondary School", "High School",
        "Associate Degree", "Bachelor's Degree", "Master's Degree", "Doctorate"
    ],
    'EXTRACURRICULAR_PARTICIPATION' : [
        "Sports", "Music", "Art", "Debate", "Drama", "Science Club", "Volunteer Work",
        "Robotics", "Coding Club", "None"
    ],
    'FIRST_NAMES_MALE' : [
        "Aarav", "Vivaan", "Aditya", "Rohan", "Kartik", "Arjun", "Krishna",
        "Rishi", "Kabir", "Shaurya", "Vihaan", "Aryan", "Aarush", "Adarsh",
        "Dhruv", "Sai", "Ansh", "Ishaan", "Raghav", "Dev"
    ],
    'FIRST_NAMES_FEMALE' : [
        "Ananya", "Ishita", "Sneha", "Diya", "Mira", "Tara", "Sanya",
        "Anika", "Myra", "Isha", "Kiara", "Riddhi", "Shruti", "Priya",
        "Meera", "Ishani", "Kavya", "Anvi", "Tania", "Rhea"
    ],
    'MIDDLE_NAMES' : [
    "Raj", "Arjun", "Karthik", "Adarsh", "Gaurav", "Nikhil", "Deepak", "Sanjay",
    "Ashok", "Bharat", "Dilip", "Mohan", "Vijay", "Suresh", "Ramesh", "Anil",
    "Sunil", "Harish", "Vasant", "Kamal"
    ],
    'LAST_NAMES' : [
        "Sharma", "Singh", "Iyer", "Patel", "Gupta", "Rao", "Mehta", "Nair",
        "Verma", "Joshi", "Kapoor", "Reddy", "Choudhury", "Bhatia", "Desai",
        "Malhotra", "Dutta", "Sengupta", "Bhatt", "Menon"
    ],
    'SOCIOECONOMIC_STATUS' : ['Low', 'Medium', 'High'],
    'TRANSPORT_MODE' : ['Walk', 'Bicycle', 'Bus', 'Car', 'Metro', 'Other'],
    'LUNCH_TYPE' : ['Home', 'School', 'Cafeteria', 'Packed'],
    'STUDY_HOURS_PER_WEEK' : (0, 40),
    'EXAM_ATTEMPTS' : (1, 5),
    'SCHOOL_TYPE' : ['Public', 'Private', 'Charter', 'International'],
    'INTERNET_ACCESS' : ['Yes', 'No'],
    'TUTORING' : ['Yes', 'No'],
    'SPORTS_SCORE' : (0, 100),
    'ART_SCORE' : (0, 100),
    'MUSIC_SCORE' : (0, 100)
}
RANGES['ALL_NAMES'] = RANGES['FIRST_NAMES_MALE'] + RANGES['FIRST_NAMES_FEMALE']

In [4]:
data = dict()
def create_ndata(key, float=False,suffix=str()):
    if not float:
            size = NUM_ROWS
            data[key+suffix] = np.asarray([
            np.random.randint(*RANGES[key],
                                size = NUM_ROWS,
                            )
            ])
    else:
            size = NUM_ROWS
            data[key+suffix] = np.asarray([
            np.round(np.random.uniform(*RANGES[key],
                                size = NUM_ROWS,
                            )
                     ,5)
            ])





def create_sdata(key, suffix=str(), weights=None, anchor=dict(), corresp=None):
    size = NUM_ROWS
    if (not corresp) or (not anchor):
        data[key+suffix] = np.asarray([
                                np.random.choice(RANGES[key],
                                size = NUM_ROWS,
                                p = weights
                                )
                            ])
    else:
        data[key+suffix] = np.asarray([
                                np.random.choice(RANGES[key],
                                size = NUM_ROWS
                                )
                            ])

        #yn = {k : v for k,v in zip([ele for ele in range(0,size) if data[key+suffix][ele] in RANGES[v]],list(anchor.keys()))}
        yn = dict()
        for ele in RANGES[key+suffix]:
            for k in anchor:
                if ele in RANGES[k]:
                    yn[ele] = k

        data[corresp] = np.asarray([
                                np.random.choice(RANGES[corresp],
                                size = 1,
                                p = anchor[yn[col]]
                                )
                                for col in data[key+suffix].flatten()
                            ]).reshape(1,-1)



nkeys = [key for key in RANGES.keys() if type(RANGES[key][0]) is not str ]
skeys = [key for key in RANGES.keys() if type(RANGES[key][0]) is str ]

In [5]:
nkeys

['STUDENT_IDS',
 'MATH_SCORE',
 'PHYSICS_SCORE',
 'CHEMISTRY_SCORE',
 'BIOLOGY_SCORE',
 'ATTENDANCE',
 'PERCENTILE',
 'STUDY_HOURS_PER_WEEK',
 'EXAM_ATTEMPTS',
 'SPORTS_SCORE',
 'ART_SCORE',
 'MUSIC_SCORE']

In [6]:
skeys

['GENDER',
 'PARENT_EDUCATION',
 'EXTRACURRICULAR_PARTICIPATION',
 'FIRST_NAMES_MALE',
 'FIRST_NAMES_FEMALE',
 'MIDDLE_NAMES',
 'LAST_NAMES',
 'SOCIOECONOMIC_STATUS',
 'TRANSPORT_MODE',
 'LUNCH_TYPE',
 'SCHOOL_TYPE',
 'INTERNET_ACCESS',
 'TUTORING',
 'ALL_NAMES']

In [7]:
list(map(lambda nk : create_ndata(nk,float= nk in ['PERCENTILE','ATTENDANCE']),nkeys))

[None, None, None, None, None, None, None, None, None, None, None, None]

In [8]:
data

{'STUDENT_IDS': array([[26778998, 26649040, 26107370, ..., 26645433, 26420523, 26344365]]),
 'MATH_SCORE': array([[249, 156, 148, ..., 136, 237,  19]]),
 'PHYSICS_SCORE': array([[168,  72, 256, ..., 202, 138, 121]]),
 'CHEMISTRY_SCORE': array([[ 16,   1, 133, ..., 127, 179,   5]]),
 'BIOLOGY_SCORE': array([[ 84, 194, 226, ...,  32,   1, 117]]),
 'ATTENDANCE': array([[ 2.46854, 19.39528, 48.95793, ..., 42.16829, 19.15311, 18.38803]]),
 'PERCENTILE': array([[62.13823, 81.11401, 24.09342, ..., 74.3417 , 75.97316, 97.75443]]),
 'STUDY_HOURS_PER_WEEK': array([[10, 35, 37, ..., 33, 34, 25]]),
 'EXAM_ATTEMPTS': array([[1, 2, 3, ..., 2, 4, 4]]),
 'SPORTS_SCORE': array([[25, 99, 38, ..., 48, 36, 55]]),
 'ART_SCORE': array([[14, 90, 79, ..., 66, 86,  0]]),
 'MUSIC_SCORE': array([[83, 62, 92, ...,  7, 37,  9]])}

In [9]:
list(map(create_sdata,[sk for sk in skeys if sk not in ['FIRST_NAMES_FEMALE','FIRST_NAMES_MALE','GENDER']]))

[None, None, None, None, None, None, None, None, None, None, None]

In [10]:
data

{'STUDENT_IDS': array([[26778998, 26649040, 26107370, ..., 26645433, 26420523, 26344365]]),
 'MATH_SCORE': array([[249, 156, 148, ..., 136, 237,  19]]),
 'PHYSICS_SCORE': array([[168,  72, 256, ..., 202, 138, 121]]),
 'CHEMISTRY_SCORE': array([[ 16,   1, 133, ..., 127, 179,   5]]),
 'BIOLOGY_SCORE': array([[ 84, 194, 226, ...,  32,   1, 117]]),
 'ATTENDANCE': array([[ 2.46854, 19.39528, 48.95793, ..., 42.16829, 19.15311, 18.38803]]),
 'PERCENTILE': array([[62.13823, 81.11401, 24.09342, ..., 74.3417 , 75.97316, 97.75443]]),
 'STUDY_HOURS_PER_WEEK': array([[10, 35, 37, ..., 33, 34, 25]]),
 'EXAM_ATTEMPTS': array([[1, 2, 3, ..., 2, 4, 4]]),
 'SPORTS_SCORE': array([[25, 99, 38, ..., 48, 36, 55]]),
 'ART_SCORE': array([[14, 90, 79, ..., 66, 86,  0]]),
 'MUSIC_SCORE': array([[83, 62, 92, ...,  7, 37,  9]]),
 'PARENT_EDUCATION': array([['Primary School', 'High School', "Bachelor's Degree", ...,
         'No formal education', 'Doctorate', 'Secondary School']],
       dtype='<U19'),
 'EXTRACURRICULAR_PARTICIPATION': array([['Science Club', 'Drama', 'Music', ..., 'Coding Club', 'Debate',
         'Volunteer Work']], dtype='<U14'),
 'MIDDLE_NAMES': array([['Gaurav', 'Vasant', 'Nikhil', ..., 'Raj', 'Vasant', 'Dilip']],
       dtype='<U7'),
 'LAST_NAMES': array([['Patel', 'Bhatt', 'Reddy', ..., 'Patel', 'Joshi', 'Joshi']],
       dtype='<U9'),
 'SOCIOECONOMIC_STATUS': array([['Low', 'High', 'Low', ..., 'High', 'Medium', 'High']], dtype='<U6'),
 'TRANSPORT_MODE': array([['Other', 'Bicycle', 'Walk', ..., 'Other', 'Other', 'Other']],
       dtype='<U7'),
 'LUNCH_TYPE': array([['Home', 'School', 'Cafeteria', ..., 'Packed', 'Packed', 'School']],
       dtype='<U9'),
 'SCHOOL_TYPE': array([['Charter', 'Private', 'Public', ..., 'Private', 'Charter',
         'Public']], dtype='<U13'),
 'INTERNET_ACCESS': array([['No', 'Yes', 'Yes', ..., 'No', 'No', 'No']], dtype='<U3'),
 'TUTORING': array([['Yes', 'Yes', 'Yes', ..., 'Yes', 'No', 'No']], dtype='<U3'),
 'ALL_NAMES': array([['Kartik', 'Dev', 'Dhruv', ..., 'Rhea', 'Ansh', 'Kavya']],
       dtype='<U7')}

In [11]:
skeys

['GENDER',
 'PARENT_EDUCATION',
 'EXTRACURRICULAR_PARTICIPATION',
 'FIRST_NAMES_MALE',
 'FIRST_NAMES_FEMALE',
 'MIDDLE_NAMES',
 'LAST_NAMES',
 'SOCIOECONOMIC_STATUS',
 'TRANSPORT_MODE',
 'LUNCH_TYPE',
 'SCHOOL_TYPE',
 'INTERNET_ACCESS',
 'TUTORING',
 'ALL_NAMES']

In [12]:
list(map(lambda sk: create_sdata(sk, '', None,{'FIRST_NAMES_MALE':[0.8,0.0,0.2],'FIRST_NAMES_FEMALE':[0.0,0.8,0.2]},'GENDER'), skeys[-1:]))

[None]

In [13]:
data

{'STUDENT_IDS': array([[26778998, 26649040, 26107370, ..., 26645433, 26420523, 26344365]]),
 'MATH_SCORE': array([[249, 156, 148, ..., 136, 237,  19]]),
 'PHYSICS_SCORE': array([[168,  72, 256, ..., 202, 138, 121]]),
 'CHEMISTRY_SCORE': array([[ 16,   1, 133, ..., 127, 179,   5]]),
 'BIOLOGY_SCORE': array([[ 84, 194, 226, ...,  32,   1, 117]]),
 'ATTENDANCE': array([[ 2.46854, 19.39528, 48.95793, ..., 42.16829, 19.15311, 18.38803]]),
 'PERCENTILE': array([[62.13823, 81.11401, 24.09342, ..., 74.3417 , 75.97316, 97.75443]]),
 'STUDY_HOURS_PER_WEEK': array([[10, 35, 37, ..., 33, 34, 25]]),
 'EXAM_ATTEMPTS': array([[1, 2, 3, ..., 2, 4, 4]]),
 'SPORTS_SCORE': array([[25, 99, 38, ..., 48, 36, 55]]),
 'ART_SCORE': array([[14, 90, 79, ..., 66, 86,  0]]),
 'MUSIC_SCORE': array([[83, 62, 92, ...,  7, 37,  9]]),
 'PARENT_EDUCATION': array([['Primary School', 'High School', "Bachelor's Degree", ...,
         'No formal education', 'Doctorate', 'Secondary School']],
       dtype='<U19'),
 'EXTRACURRICULAR_PARTICIPATION': array([['Science Club', 'Drama', 'Music', ..., 'Coding Club', 'Debate',
         'Volunteer Work']], dtype='<U14'),
 'MIDDLE_NAMES': array([['Gaurav', 'Vasant', 'Nikhil', ..., 'Raj', 'Vasant', 'Dilip']],
       dtype='<U7'),
 'LAST_NAMES': array([['Patel', 'Bhatt', 'Reddy', ..., 'Patel', 'Joshi', 'Joshi']],
       dtype='<U9'),
 'SOCIOECONOMIC_STATUS': array([['Low', 'High', 'Low', ..., 'High', 'Medium', 'High']], dtype='<U6'),
 'TRANSPORT_MODE': array([['Other', 'Bicycle', 'Walk', ..., 'Other', 'Other', 'Other']],
       dtype='<U7'),
 'LUNCH_TYPE': array([['Home', 'School', 'Cafeteria', ..., 'Packed', 'Packed', 'School']],
       dtype='<U9'),
 'SCHOOL_TYPE': array([['Charter', 'Private', 'Public', ..., 'Private', 'Charter',
         'Public']], dtype='<U13'),
 'INTERNET_ACCESS': array([['No', 'Yes', 'Yes', ..., 'No', 'No', 'No']], dtype='<U3'),
 'TUTORING': array([['Yes', 'Yes', 'Yes', ..., 'Yes', 'No', 'No']], dtype='<U3'),
 'ALL_NAMES': array([['Anika', 'Tara', 'Aarav', ..., 'Rishi', 'Krishna', 'Rohan']],
       dtype='<U7'),
 'GENDER': array([['OTHER', 'OTHER', 'MALE', ..., 'MALE', 'OTHER', 'MALE']],
       dtype='<U6')}

In [14]:
clean_dict = {}

for key, value in data.items():
    if isinstance(value, np.ndarray):
        if len(value.shape) == 2 and value.shape[0] == 1:
            clean_dict[key] = value.flatten()
        else:
            clean_dict[key] = value  
    else:
        clean_dict[key] = value
        
display(clean_dict)
df = pd.DataFrame(clean_dict)

print(df.head())
print(df.shape)

{'STUDENT_IDS': array([26778998, 26649040, 26107370, ..., 26645433, 26420523, 26344365]),
 'MATH_SCORE': array([249, 156, 148, ..., 136, 237,  19]),
 'PHYSICS_SCORE': array([168,  72, 256, ..., 202, 138, 121]),
 'CHEMISTRY_SCORE': array([ 16,   1, 133, ..., 127, 179,   5]),
 'BIOLOGY_SCORE': array([ 84, 194, 226, ...,  32,   1, 117]),
 'ATTENDANCE': array([ 2.46854, 19.39528, 48.95793, ..., 42.16829, 19.15311, 18.38803]),
 'PERCENTILE': array([62.13823, 81.11401, 24.09342, ..., 74.3417 , 75.97316, 97.75443]),
 'STUDY_HOURS_PER_WEEK': array([10, 35, 37, ..., 33, 34, 25]),
 'EXAM_ATTEMPTS': array([1, 2, 3, ..., 2, 4, 4]),
 'SPORTS_SCORE': array([25, 99, 38, ..., 48, 36, 55]),
 'ART_SCORE': array([14, 90, 79, ..., 66, 86,  0]),
 'MUSIC_SCORE': array([83, 62, 92, ...,  7, 37,  9]),
 'PARENT_EDUCATION': array(['Primary School', 'High School', "Bachelor's Degree", ...,
        'No formal education', 'Doctorate', 'Secondary School'],
       dtype='<U19'),
 'EXTRACURRICULAR_PARTICIPATION': array(['Science Club', 'Drama', 'Music', ..., 'Coding Club', 'Debate',
        'Volunteer Work'], dtype='<U14'),
 'MIDDLE_NAMES': array(['Gaurav', 'Vasant', 'Nikhil', ..., 'Raj', 'Vasant', 'Dilip'],
       dtype='<U7'),
 'LAST_NAMES': array(['Patel', 'Bhatt', 'Reddy', ..., 'Patel', 'Joshi', 'Joshi'],
       dtype='<U9'),
 'SOCIOECONOMIC_STATUS': array(['Low', 'High', 'Low', ..., 'High', 'Medium', 'High'], dtype='<U6'),
 'TRANSPORT_MODE': array(['Other', 'Bicycle', 'Walk', ..., 'Other', 'Other', 'Other'],
       dtype='<U7'),
 'LUNCH_TYPE': array(['Home', 'School', 'Cafeteria', ..., 'Packed', 'Packed', 'School'],
       dtype='<U9'),
 'SCHOOL_TYPE': array(['Charter', 'Private', 'Public', ..., 'Private', 'Charter',
        'Public'], dtype='<U13'),
 'INTERNET_ACCESS': array(['No', 'Yes', 'Yes', ..., 'No', 'No', 'No'], dtype='<U3'),
 'TUTORING': array(['Yes', 'Yes', 'Yes', ..., 'Yes', 'No', 'No'], dtype='<U3'),
 'ALL_NAMES': array(['Anika', 'Tara', 'Aarav', ..., 'Rishi', 'Krishna', 'Rohan'],
       dtype='<U7'),
 'GENDER': array(['OTHER', 'OTHER', 'MALE', ..., 'MALE', 'OTHER', 'MALE'],
       dtype='<U6')}

   STUDENT_IDS  MATH_SCORE  PHYSICS_SCORE  CHEMISTRY_SCORE  BIOLOGY_SCORE  \
0     26778998         249            168               16             84
1     26649040         156             72                1            194
2     26107370         148            256              133            226
3     26100961         276             33              180             15
4     26442601         267            295               55             85

   ATTENDANCE  PERCENTILE  STUDY_HOURS_PER_WEEK  EXAM_ATTEMPTS  SPORTS_SCORE  \
0     2.46854    62.13823                    10              1            25
1    19.39528    81.11401                    35              2            99
2    48.95793    24.09342                    37              3            38
3    17.54283    11.02250                     8              3            16
4    72.12814    26.47400                    19              1            24

   ...  MIDDLE_NAMES  LAST_NAMES SOCIOECONOMIC_STATUS TRANSPORT_MODE  \
0  ...        Gaurav       Patel                  Low          Other
1  ...        Vasant       Bhatt                 High        Bicycle
2  ...        Nikhil       Reddy                  Low           Walk
3  ...       Karthik       Singh               Medium           Walk
4  ...        Bharat       Singh                 High           Walk

  LUNCH_TYPE SCHOOL_TYPE INTERNET_ACCESS TUTORING ALL_NAMES  GENDER
0       Home     Charter              No      Yes     Anika   OTHER
1     School     Private             Yes      Yes      Tara   OTHER
2  Cafeteria      Public             Yes      Yes     Aarav    MALE
3     Packed     Charter              No       No     Tania  FEMALE
4     Packed      Public              No      Yes     Aarav    MALE

[5 rows x 24 columns]
(10000, 24)

In [15]:
display(df)

,STUDENT_IDS,MATH_SCORE,PHYSICS_SCORE,CHEMISTRY_SCORE,BIOLOGY_SCORE,ATTENDANCE,PERCENTILE,STUDY_HOURS_PER_WEEK,EXAM_ATTEMPTS,SPORTS_SCORE,...,MIDDLE_NAMES,LAST_NAMES,SOCIOECONOMIC_STATUS,TRANSPORT_MODE,LUNCH_TYPE,SCHOOL_TYPE,INTERNET_ACCESS,TUTORING,ALL_NAMES,GENDER
0,26778998,249,168,16,84,2.46854,62.13823,10,1,25,...,Gaurav,Patel,Low,Other,Home,Charter,No,Yes,Anika,OTHER
1,26649040,156,72,1,194,19.39528,81.11401,35,2,99,...,Vasant,Bhatt,High,Bicycle,School,Private,Yes,Yes,Tara,OTHER
2,26107370,148,256,133,226,48.95793,24.09342,37,3,38,...,Nikhil,Reddy,Low,Walk,Cafeteria,Public,Yes,Yes,Aarav,MALE
3,26100961,276,33,180,15,17.54283,11.02250,8,3,16,...,Karthik,Singh,Medium,Walk,Packed,Charter,No,No,Tania,FEMALE
4,26442601,267,295,55,85,72.12814,26.47400,19,1,24,...,Bharat,Singh,High,Walk,Packed,Public,No,Yes,Aarav,MALE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,26247788,203,36,66,259,94.93103,64.24536,3,4,60,...,Ashok,Singh,High,Walk,Cafeteria,Charter,No,No,Riddhi,FEMALE
9996,26858915,255,39,83,0,45.74113,58.81036,38,2,60,...,Anil,Bhatt,Low,Bus,School,International,No,No,Ansh,MALE
9997,26645433,136,202,127,32,42.16829,74.34170,33,2,48,...,Raj,Patel,High,Other,Packed,Private,No,Yes,Rishi,MALE
9998,26420523,237,138,179,1,19.15311,75.97316,34,4,36,...,Vasant,Joshi,Medium,Other,Packed,Charter,No,No,Krishna,OTHER
9999,26344365,19,121,5,117,18.38803,97.75443,25,4,55,...,Dilip,Joshi,High,Other,School,Public,No,No,Rohan,MALE

In [16]:

df

,STUDENT_IDS,MATH_SCORE,PHYSICS_SCORE,CHEMISTRY_SCORE,BIOLOGY_SCORE,ATTENDANCE,PERCENTILE,STUDY_HOURS_PER_WEEK,EXAM_ATTEMPTS,SPORTS_SCORE,...,MIDDLE_NAMES,LAST_NAMES,SOCIOECONOMIC_STATUS,TRANSPORT_MODE,LUNCH_TYPE,SCHOOL_TYPE,INTERNET_ACCESS,TUTORING,ALL_NAMES,GENDER
0,26778998,249,168,16,84,2.46854,62.13823,10,1,25,...,Gaurav,Patel,Low,Other,Home,Charter,No,Yes,Anika,OTHER
1,26649040,156,72,1,194,19.39528,81.11401,35,2,99,...,Vasant,Bhatt,High,Bicycle,School,Private,Yes,Yes,Tara,OTHER
2,26107370,148,256,133,226,48.95793,24.09342,37,3,38,...,Nikhil,Reddy,Low,Walk,Cafeteria,Public,Yes,Yes,Aarav,MALE
3,26100961,276,33,180,15,17.54283,11.02250,8,3,16,...,Karthik,Singh,Medium,Walk,Packed,Charter,No,No,Tania,FEMALE
4,26442601,267,295,55,85,72.12814,26.47400,19,1,24,...,Bharat,Singh,High,Walk,Packed,Public,No,Yes,Aarav,MALE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,26247788,203,36,66,259,94.93103,64.24536,3,4,60,...,Ashok,Singh,High,Walk,Cafeteria,Charter,No,No,Riddhi,FEMALE
9996,26858915,255,39,83,0,45.74113,58.81036,38,2,60,...,Anil,Bhatt,Low,Bus,School,International,No,No,Ansh,MALE
9997,26645433,136,202,127,32,42.16829,74.34170,33,2,48,...,Raj,Patel,High,Other,Packed,Private,No,Yes,Rishi,MALE
9998,26420523,237,138,179,1,19.15311,75.97316,34,4,36,...,Vasant,Joshi,Medium,Other,Packed,Charter,No,No,Krishna,OTHER
9999,26344365,19,121,5,117,18.38803,97.75443,25,4,55,...,Dilip,Joshi,High,Other,School,Public,No,No,Rohan,MALE

In [17]:
# Sets axis 1 (columns) to a range starting at 0
ALL = df.pop('ALL_NAMES')
df.insert(15,'ALL_NAMES',ALL)

In [18]:
df

,STUDENT_IDS,MATH_SCORE,PHYSICS_SCORE,CHEMISTRY_SCORE,BIOLOGY_SCORE,ATTENDANCE,PERCENTILE,STUDY_HOURS_PER_WEEK,EXAM_ATTEMPTS,SPORTS_SCORE,...,MIDDLE_NAMES,ALL_NAMES,LAST_NAMES,SOCIOECONOMIC_STATUS,TRANSPORT_MODE,LUNCH_TYPE,SCHOOL_TYPE,INTERNET_ACCESS,TUTORING,GENDER
0,26778998,249,168,16,84,2.46854,62.13823,10,1,25,...,Gaurav,Anika,Patel,Low,Other,Home,Charter,No,Yes,OTHER
1,26649040,156,72,1,194,19.39528,81.11401,35,2,99,...,Vasant,Tara,Bhatt,High,Bicycle,School,Private,Yes,Yes,OTHER
2,26107370,148,256,133,226,48.95793,24.09342,37,3,38,...,Nikhil,Aarav,Reddy,Low,Walk,Cafeteria,Public,Yes,Yes,MALE
3,26100961,276,33,180,15,17.54283,11.02250,8,3,16,...,Karthik,Tania,Singh,Medium,Walk,Packed,Charter,No,No,FEMALE
4,26442601,267,295,55,85,72.12814,26.47400,19,1,24,...,Bharat,Aarav,Singh,High,Walk,Packed,Public,No,Yes,MALE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,26247788,203,36,66,259,94.93103,64.24536,3,4,60,...,Ashok,Riddhi,Singh,High,Walk,Cafeteria,Charter,No,No,FEMALE
9996,26858915,255,39,83,0,45.74113,58.81036,38,2,60,...,Anil,Ansh,Bhatt,Low,Bus,School,International,No,No,MALE
9997,26645433,136,202,127,32,42.16829,74.34170,33,2,48,...,Raj,Rishi,Patel,High,Other,Packed,Private,No,Yes,MALE
9998,26420523,237,138,179,1,19.15311,75.97316,34,4,36,...,Vasant,Krishna,Joshi,Medium,Other,Packed,Charter,No,No,OTHER
9999,26344365,19,121,5,117,18.38803,97.75443,25,4,55,...,Dilip,Rohan,Joshi,High,Other,School,Public,No,No,MALE

In [19]:
#df['DETENTION'] = df['ATTENDANCE'] < 75
df['DETENTION'] = np.where(df['ATTENDANCE'] < 75 , 'YES' , 'NO')
df

,STUDENT_IDS,MATH_SCORE,PHYSICS_SCORE,CHEMISTRY_SCORE,BIOLOGY_SCORE,ATTENDANCE,PERCENTILE,STUDY_HOURS_PER_WEEK,EXAM_ATTEMPTS,SPORTS_SCORE,...,ALL_NAMES,LAST_NAMES,SOCIOECONOMIC_STATUS,TRANSPORT_MODE,LUNCH_TYPE,SCHOOL_TYPE,INTERNET_ACCESS,TUTORING,GENDER,DETENTION
0,26778998,249,168,16,84,2.46854,62.13823,10,1,25,...,Anika,Patel,Low,Other,Home,Charter,No,Yes,OTHER,YES
1,26649040,156,72,1,194,19.39528,81.11401,35,2,99,...,Tara,Bhatt,High,Bicycle,School,Private,Yes,Yes,OTHER,YES
2,26107370,148,256,133,226,48.95793,24.09342,37,3,38,...,Aarav,Reddy,Low,Walk,Cafeteria,Public,Yes,Yes,MALE,YES
3,26100961,276,33,180,15,17.54283,11.02250,8,3,16,...,Tania,Singh,Medium,Walk,Packed,Charter,No,No,FEMALE,YES
4,26442601,267,295,55,85,72.12814,26.47400,19,1,24,...,Aarav,Singh,High,Walk,Packed,Public,No,Yes,MALE,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,26247788,203,36,66,259,94.93103,64.24536,3,4,60,...,Riddhi,Singh,High,Walk,Cafeteria,Charter,No,No,FEMALE,NO
9996,26858915,255,39,83,0,45.74113,58.81036,38,2,60,...,Ansh,Bhatt,Low,Bus,School,International,No,No,MALE,YES
9997,26645433,136,202,127,32,42.16829,74.34170,33,2,48,...,Rishi,Patel,High,Other,Packed,Private,No,Yes,MALE,YES
9998,26420523,237,138,179,1,19.15311,75.97316,34,4,36,...,Krishna,Joshi,Medium,Other,Packed,Charter,No,No,OTHER,YES
9999,26344365,19,121,5,117,18.38803,97.75443,25,4,55,...,Rohan,Joshi,High,Other,School,Public,No,No,MALE,YES

In [20]:
df['MATH_SCORE']

0       249
1       156
2       148
3       276
4       267
       ...
9995    203
9996    255
9997    136
9998    237
9999     19
Name: MATH_SCORE, Length: 10000, dtype: int64

In [21]:
df['PHYSICS_SCORE']

0       168
1        72
2       256
3        33
4       295
       ...
9995     36
9996     39
9997    202
9998    138
9999    121
Name: PHYSICS_SCORE, Length: 10000, dtype: int64

In [22]:
df['CHEMISTRY_SCORE']

0        16
1         1
2       133
3       180
4        55
       ...
9995     66
9996     83
9997    127
9998    179
9999      5
Name: CHEMISTRY_SCORE, Length: 10000, dtype: int64

In [23]:
df['BIOLOGY_SCORE']

0        84
1       194
2       226
3        15
4        85
       ...
9995    259
9996      0
9997     32
9998      1
9999    117
Name: BIOLOGY_SCORE, Length: 10000, dtype: int64

In [24]:
df['SPORTS_SCORE']

0       25
1       99
2       38
3       16
4       24
        ..
9995    60
9996    60
9997    48
9998    36
9999    55
Name: SPORTS_SCORE, Length: 10000, dtype: int64

In [25]:
df['ART_SCORE']

0       14
1       90
2       79
3       58
4       59
        ..
9995    79
9996    61
9997    66
9998    86
9999     0
Name: ART_SCORE, Length: 10000, dtype: int64

In [26]:
df['MUSIC_SCORE']

0       83
1       62
2       92
3       26
4       91
        ..
9995    36
9996    50
9997     7
9998    37
9999     9
Name: MUSIC_SCORE, Length: 10000, dtype: int64

In [27]:
df['TOTAL_MARKS'] = df[['MATH_SCORE','PHYSICS_SCORE','CHEMISTRY_SCORE','BIOLOGY_SCORE']].sum(axis=1) #AXIS 1 COLUMNS SO COLLAPSE COLS
df['TOTAL_MARKS']

0       517
1       423
2       763
3       504
4       702
       ...
9995    564
9996    377
9997    497
9998    555
9999    262
Name: TOTAL_MARKS, Length: 10000, dtype: int64

In [28]:
import numpy as np

df['GRADE'] = np.where((df['TOTAL_MARKS'] >= 0) & (df['TOTAL_MARKS'] < 525), 'F',
              np.where((df['TOTAL_MARKS'] >= 525) & (df['TOTAL_MARKS'] < 625), 'P',
              np.where((df['TOTAL_MARKS'] >= 625) & (df['TOTAL_MARKS'] < 725), 'C',
              np.where((df['TOTAL_MARKS'] >= 725) & (df['TOTAL_MARKS'] < 825), 'B',
              np.where((df['TOTAL_MARKS'] >= 825) & (df['TOTAL_MARKS'] < 925), 'B+',
              np.where((df['TOTAL_MARKS'] >= 925) & (df['TOTAL_MARKS'] < 1025), 'A',
              np.where((df['TOTAL_MARKS'] >= 1025) & (df['TOTAL_MARKS'] < 1125), 'A+',
              np.where(df['TOTAL_MARKS'] >= 1125, 'O', 'F'))))))))
df['GRADE']

0       F
1       F
2       B
3       F
4       C
       ..
9995    P
9996    F
9997    F
9998    P
9999    F
Name: GRADE, Length: 10000, dtype: object

In [29]:

# better way

bins = [0, 300, 625, 725, 825, 925, 1025, 1125, 1500]
labels = ['F', 'P', 'C', 'B', 'B+', 'A', 'A+', 'O']

df['GRADE'] = pd.cut(df['TOTAL_MARKS'],bins=bins,labels=labels,include_lowest=True)

df['GRADE']

0       P
1       P
2       B
3       P
4       C
       ..
9995    P
9996    P
9997    P
9998    P
9999    F
Name: GRADE, Length: 10000, dtype: category
Categories (8, object): ['F' < 'P' < 'C' < 'B' < 'B+' < 'A' < 'A+' < 'O']

In [30]:
df['STUDENT_IDS'] = 'CSETES0' + df['STUDENT_IDS'].astype(str)

In [31]:
df['STUDENT_IDS'].drop_duplicates(keep="first",inplace=True)

In [32]:
df

,STUDENT_IDS,MATH_SCORE,PHYSICS_SCORE,CHEMISTRY_SCORE,BIOLOGY_SCORE,ATTENDANCE,PERCENTILE,STUDY_HOURS_PER_WEEK,EXAM_ATTEMPTS,SPORTS_SCORE,...,SOCIOECONOMIC_STATUS,TRANSPORT_MODE,LUNCH_TYPE,SCHOOL_TYPE,INTERNET_ACCESS,TUTORING,GENDER,DETENTION,TOTAL_MARKS,GRADE
0,CSETES026778998,249,168,16,84,2.46854,62.13823,10,1,25,...,Low,Other,Home,Charter,No,Yes,OTHER,YES,517,P
1,CSETES026649040,156,72,1,194,19.39528,81.11401,35,2,99,...,High,Bicycle,School,Private,Yes,Yes,OTHER,YES,423,P
2,CSETES026107370,148,256,133,226,48.95793,24.09342,37,3,38,...,Low,Walk,Cafeteria,Public,Yes,Yes,MALE,YES,763,B
3,CSETES026100961,276,33,180,15,17.54283,11.02250,8,3,16,...,Medium,Walk,Packed,Charter,No,No,FEMALE,YES,504,P
4,CSETES026442601,267,295,55,85,72.12814,26.47400,19,1,24,...,High,Walk,Packed,Public,No,Yes,MALE,YES,702,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,CSETES026247788,203,36,66,259,94.93103,64.24536,3,4,60,...,High,Walk,Cafeteria,Charter,No,No,FEMALE,NO,564,P
9996,CSETES026858915,255,39,83,0,45.74113,58.81036,38,2,60,...,Low,Bus,School,International,No,No,MALE,YES,377,P
9997,CSETES026645433,136,202,127,32,42.16829,74.34170,33,2,48,...,High,Other,Packed,Private,No,Yes,MALE,YES,497,P
9998,CSETES026420523,237,138,179,1,19.15311,75.97316,34,4,36,...,Medium,Other,Packed,Charter,No,No,OTHER,YES,555,P
9999,CSETES026344365,19,121,5,117,18.38803,97.75443,25,4,55,...,High,Other,School,Public,No,No,MALE,YES,262,F